### ISSUE TITLE
Add link to the GitHub project in a suitable place in the UI

### ISSUE THREAD

**Issue by M4rtinK** [yarda/printrun-webmon#6]
Add link to the GitHub project in a suitable place in the UI (bottom left ?). This would make it easier to know the upstream project behind the print monitoring UI. :)

**Comment by yarda** [comment]
Maybe not optimal, but feel free to PRs better/nicer integration into UI  :)

**Comment by yarda** [comment]
Maybe just '?' (or 'Π' to honor Angella Bennett :) in the right bottom corner would suffice.
